// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1alpha1/lifecycle/lifecycle.proto

package lifecyclev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LifecycleState describes where the node process is in its own
// stop/restart sequence. This is distinct from SyncStatus, which describes
// the node's position relative to the chain.
type LifecycleState int32

const (
	LifecycleState_LIFECYCLE_STATE_UNSPECIFIED LifecycleState = 0
	// The node is running normally and accepting requests.
	LifecycleState_LIFECYCLE_STATE_RUNNING LifecycleState = 1
	// A graceful stop is in progress: sync has ceased and the coordinator is
	// draining connections and flushing the database before exit.
	LifecycleState_LIFECYCLE_STATE_STOPPING LifecycleState = 2
	// A graceful restart is in progress; the same shutdown sequence as
	// STOPPING is running, after which the process re-executes.
	LifecycleState_LIFECYCLE_STATE_RESTARTING LifecycleState = 3
)

// Enum value maps for LifecycleState.
var (
	LifecycleState_name = map[int32]string{
		0: "LIFECYCLE_STATE_UNSPECIFIED",
		1: "LIFECYCLE_STATE_RUNNING",
		2: "LIFECYCLE_STATE_STOPPING",
		3: "LIFECYCLE_STATE_RESTARTING",
	}
	LifecycleState_value = map[string]int32{
		"LIFECYCLE_STATE_UNSPECIFIED": 0,
		"LIFECYCLE_STATE_RUNNING":     1,
		"LIFECYCLE_STATE_STOPPING":    2,
		"LIFECYCLE_STATE_RESTARTING":  3,
	}
)

func (x LifecycleState) Enum() *LifecycleState {
	p := new(LifecycleState)
	*p = x
	return p
}

func (x LifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_lifecycle_lifecycle_proto_enumTypes[0].Descriptor()
}

func (LifecycleState) Type() protoreflect.EnumType {
	return &file_v1alpha1_lifecycle_lifecycle_proto_enumTypes[0]
}

func (x LifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleState.Descriptor instead.
func (LifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{0}
}

// HealthStatus is a coarse-grained health signal for the node process,
// independent of chain synchronization progress.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	// The node is fully operational.
	HealthStatus_HEALTH_STATUS_HEALTHY HealthStatus = 1
	// The node is operational but impaired (e.g. a non-critical subsystem is
	// failing, or sync has stalled).
	HealthStatus_HEALTH_STATUS_DEGRADED HealthStatus = 2
	// The node cannot perform its core function.
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_lifecycle_lifecycle_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_lifecycle_lifecycle_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{1}
}

// BlockRef identifies a block by one or more of hash, slot, or block
// number. This message is only used as output (via SyncStatus.tip); no
// LifecycleService RPC accepts it as input. The server MUST set at least
// one field, and any fields it does set MUST agree with each other.
type BlockRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block hash as a hex-encoded string.
	Hash *string `protobuf:"bytes,1,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	// Slot number.
	Slot *uint64 `protobuf:"varint,2,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
	// Block number / height.
	BlockNumber   *uint64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRef) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *BlockRef) GetSlot() uint64 {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return 0
}

func (x *BlockRef) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

// SyncStatus describes the node's chain synchronization state.
type SyncStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the node considers itself caught up with the tip of the
	// network.
	Synced bool `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	// The node's current local chain tip. Unset if the node has not synced
	// any blocks yet.
	Tip *BlockRef `protobuf:"bytes,2,opt,name=tip,proto3,oneof" json:"tip,omitempty"`
	// Estimated slot of the network tip, if known. 0 if unknown.
	EstimatedNetworkTipSlot uint64 `protobuf:"varint,3,opt,name=estimated_network_tip_slot,json=estimatedNetworkTipSlot,proto3" json:"estimated_network_tip_slot,omitempty"`
	// Estimated number of slots behind the network tip. 0 when synced or
	// when the network tip is unknown.
	SlotsBehind   uint64 `protobuf:"varint,4,opt,name=slots_behind,json=slotsBehind,proto3" json:"slots_behind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStatus) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *SyncStatus) GetTip() *BlockRef {
	if x != nil {
		return x.Tip
	}
	return nil
}

func (x *SyncStatus) GetEstimatedNetworkTipSlot() uint64 {
	if x != nil {
		return x.EstimatedNetworkTipSlot
	}
	return 0
}

func (x *SyncStatus) GetSlotsBehind() uint64 {
	if x != nil {
		return x.SlotsBehind
	}
	return 0
}

type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum duration to allow for the graceful shutdown sequence before
	// the coordinator forces the process to exit. Unset or zero means the
	// server's configured default is used. The server returns
	// INVALID_ARGUMENT if this is negative.
	GracefulTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=graceful_timeout,json=gracefulTimeout,proto3,oneof" json:"graceful_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetGracefulTimeout() *durationpb.Duration {
	if x != nil {
		return x.GracefulTimeout
	}
	return nil
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graceful timeout that will actually be enforced: the server's
	// default when the request left graceful_timeout unset, or the
	// server's configured maximum when the request exceeded it.
	EffectiveTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=effective_timeout,json=effectiveTimeout,proto3" json:"effective_timeout,omitempty"`
	// Deadline by which the graceful sequence must finish before the
	// process is forced to exit.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetEffectiveTimeout() *durationpb.Duration {
	if x != nil {
		return x.EffectiveTimeout
	}
	return nil
}

func (x *StopResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum duration to allow for the graceful shutdown sequence before
	// the coordinator forces re-execution. Unset or zero means the server's
	// configured default is used. The server returns INVALID_ARGUMENT if
	// this is negative.
	GracefulTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=graceful_timeout,json=gracefulTimeout,proto3,oneof" json:"graceful_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *RestartRequest) GetGracefulTimeout() *durationpb.Duration {
	if x != nil {
		return x.GracefulTimeout
	}
	return nil
}

type RestartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graceful timeout that will actually be enforced: the server's
	// default when the request left graceful_timeout unset, or the
	// server's configured maximum when the request exceeded it.
	EffectiveTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=effective_timeout,json=effectiveTimeout,proto3" json:"effective_timeout,omitempty"`
	// Deadline by which the graceful sequence must finish before the
	// process is forced to re-execute.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *RestartResponse) GetEffectiveTimeout() *durationpb.Duration {
	if x != nil {
		return x.EffectiveTimeout
	}
	return nil
}

func (x *RestartResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{6}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current lifecycle state of the node process.
	State LifecycleState `protobuf:"varint,1,opt,name=state,proto3,enum=bark.v1alpha1.lifecycle.LifecycleState" json:"state,omitempty"`
	// Coarse-grained health signal.
	Health HealthStatus `protobuf:"varint,2,opt,name=health,proto3,enum=bark.v1alpha1.lifecycle.HealthStatus" json:"health,omitempty"`
	// How long the node process has been running.
	Uptime *durationpb.Duration `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Node software version (e.g. semantic version, optionally with a build
	// or commit identifier).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Chain synchronization state.
	Sync *SyncStatus `protobuf:"bytes,5,opt,name=sync,proto3" json:"sync,omitempty"`
	// Deadline by which an in-progress graceful stop or restart must finish
	// before it is forced. Only set when state is STOPPING or RESTARTING.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetState() LifecycleState {
	if x != nil {
		return x.State
	}
	return LifecycleState_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetSync() *SyncStatus {
	if x != nil {
		return x.Sync
	}
	return nil
}

func (x *GetStatusResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

var File_v1alpha1_lifecycle_lifecycle_proto protoreflect.FileDescriptor

const file_v1alpha1_lifecycle_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\"v1alpha1/lifecycle/lifecycle.proto\x12\x17bark.v1alpha1.lifecycle\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\bBlockRef\x12\x17\n" +
	"\x04hash\x18\x01 \x01(\tH\x00R\x04hash\x88\x01\x01\x12\x17\n" +
	"\x04slot\x18\x02 \x01(\x04H\x01R\x04slot\x88\x01\x01\x12&\n" +
	"\fblock_number\x18\x03 \x01(\x04H\x02R\vblockNumber\x88\x01\x01B\a\n" +
	"\x05_hashB\a\n" +
	"\x05_slotB\x0f\n" +
	"\r_block_number\"\xc6\x01\n" +
	"\n" +
	"SyncStatus\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\bR\x06synced\x128\n" +
	"\x03tip\x18\x02 \x01(\v2!.bark.v1alpha1.lifecycle.BlockRefH\x00R\x03tip\x88\x01\x01\x12;\n" +
	"\x1aestimated_network_tip_slot\x18\x03 \x01(\x04R\x17estimatedNetworkTipSlot\x12!\n" +
	"\fslots_behind\x18\x04 \x01(\x04R\vslotsBehindB\x06\n" +
	"\x04_tip\"m\n" +
	"\vStopRequest\x12I\n" +
	"\x10graceful_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x0fgracefulTimeout\x88\x01\x01B\x13\n" +
	"\x11_graceful_timeout\"\x8e\x01\n" +
	"\fStopResponse\x12F\n" +
	"\x11effective_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x10effectiveTimeout\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"p\n" +
	"\x0eRestartRequest\x12I\n" +
	"\x10graceful_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x0fgracefulTimeout\x88\x01\x01B\x13\n" +
	"\x11_graceful_timeout\"\x91\x01\n" +
	"\x0fRestartResponse\x12F\n" +
	"\x11effective_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x10effectiveTimeout\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\x12\n" +
	"\x10GetStatusRequest\"\xe1\x02\n" +
	"\x11GetStatusResponse\x12=\n" +
	"\x05state\x18\x01 \x01(\x0e2'.bark.v1alpha1.lifecycle.LifecycleStateR\x05state\x12=\n" +
	"\x06health\x18\x02 \x01(\x0e2%.bark.v1alpha1.lifecycle.HealthStatusR\x06health\x121\n" +
	"\x06uptime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x127\n" +
	"\x04sync\x18\x05 \x01(\v2#.bark.v1alpha1.lifecycle.SyncStatusR\x04sync\x12;\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01B\v\n" +
	"\t_deadline*\x8c\x01\n" +
	"\x0eLifecycleState\x12\x1f\n" +
	"\x1bLIFECYCLE_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LIFECYCLE_STATE_RUNNING\x10\x01\x12\x1c\n" +
	"\x18LIFECYCLE_STATE_STOPPING\x10\x02\x12\x1e\n" +
	"\x1aLIFECYCLE_STATE_RESTARTING\x10\x03*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\xa9\x02\n" +
	"\x10LifecycleService\x12S\n" +
	"\x04Stop\x12$.bark.v1alpha1.lifecycle.StopRequest\x1a%.bark.v1alpha1.lifecycle.StopResponse\x12\\\n" +
	"\aRestart\x12'.bark.v1alpha1.lifecycle.RestartRequest\x1a(.bark.v1alpha1.lifecycle.RestartResponse\x12b\n" +
	"\tGetStatus\x12).bark.v1alpha1.lifecycle.GetStatusRequest\x1a*.bark.v1alpha1.lifecycle.GetStatusResponseB\xf4\x01\n" +
	"\x1bcom.bark.v1alpha1.lifecycleB\x0eLifecycleProtoP\x01ZGgithub.com/blinklabs-io/bark/proto/v1alpha1/lifecycle;lifecyclev1alpha1\xa2\x02\x03BVL\xaa\x02\x17Bark.V1alpha1.Lifecycle\xca\x02\x17Bark\\V1alpha1\\Lifecycle\xe2\x02#Bark\\V1alpha1\\Lifecycle\\GPBMetadata\xea\x02\x19Bark::V1alpha1::Lifecycleb\x06proto3"

var (
	file_v1alpha1_lifecycle_lifecycle_proto_rawDescOnce sync.Once
	file_v1alpha1_lifecycle_lifecycle_proto_rawDescData []byte
)

func file_v1alpha1_lifecycle_lifecycle_proto_rawDescGZIP() []byte {
	file_v1alpha1_lifecycle_lifecycle_proto_rawDescOnce.Do(func() {
		file_v1alpha1_lifecycle_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_lifecycle_lifecycle_proto_rawDesc), len(file_v1alpha1_lifecycle_lifecycle_proto_rawDesc)))
	})
	return file_v1alpha1_lifecycle_lifecycle_proto_rawDescData
}

var file_v1alpha1_lifecycle_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1alpha1_lifecycle_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1alpha1_lifecycle_lifecycle_proto_goTypes = []any{
	(LifecycleState)(0),           // 0: bark.v1alpha1.lifecycle.LifecycleState
	(HealthStatus)(0),             // 1: bark.v1alpha1.lifecycle.HealthStatus
	(*BlockRef)(nil),              // 2: bark.v1alpha1.lifecycle.BlockRef
	(*SyncStatus)(nil),            // 3: bark.v1alpha1.lifecycle.SyncStatus
	(*StopRequest)(nil),           // 4: bark.v1alpha1.lifecycle.StopRequest
	(*StopResponse)(nil),          // 5: bark.v1alpha1.lifecycle.StopResponse
	(*RestartRequest)(nil),        // 6: bark.v1alpha1.lifecycle.RestartRequest
	(*RestartResponse)(nil),       // 7: bark.v1alpha1.lifecycle.RestartResponse
	(*GetStatusRequest)(nil),      // 8: bark.v1alpha1.lifecycle.GetStatusRequest
	(*GetStatusResponse)(nil),     // 9: bark.v1alpha1.lifecycle.GetStatusResponse
	(*durationpb.Duration)(nil),   // 10: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_v1alpha1_lifecycle_lifecycle_proto_depIdxs = []int32{
	2,  // 0: bark.v1alpha1.lifecycle.SyncStatus.tip:type_name -> bark.v1alpha1.lifecycle.BlockRef
	10, // 1: bark.v1alpha1.lifecycle.StopRequest.graceful_timeout:type_name -> google.protobuf.Duration
	10, // 2: bark.v1alpha1.lifecycle.StopResponse.effective_timeout:type_name -> google.protobuf.Duration
	11, // 3: bark.v1alpha1.lifecycle.StopResponse.deadline:type_name -> google.protobuf.Timestamp
	10, // 4: bark.v1alpha1.lifecycle.RestartRequest.graceful_timeout:type_name -> google.protobuf.Duration
	10, // 5: bark.v1alpha1.lifecycle.RestartResponse.effective_timeout:type_name -> google.protobuf.Duration
	11, // 6: bark.v1alpha1.lifecycle.RestartResponse.deadline:type_name -> google.protobuf.Timestamp
	0,  // 7: bark.v1alpha1.lifecycle.GetStatusResponse.state:type_name -> bark.v1alpha1.lifecycle.LifecycleState
	1,  // 8: bark.v1alpha1.lifecycle.GetStatusResponse.health:type_name -> bark.v1alpha1.lifecycle.HealthStatus
	10, // 9: bark.v1alpha1.lifecycle.GetStatusResponse.uptime:type_name -> google.protobuf.Duration
	3,  // 10: bark.v1alpha1.lifecycle.GetStatusResponse.sync:type_name -> bark.v1alpha1.lifecycle.SyncStatus
	11, // 11: bark.v1alpha1.lifecycle.GetStatusResponse.deadline:type_name -> google.protobuf.Timestamp
	4,  // 12: bark.v1alpha1.lifecycle.LifecycleService.Stop:input_type -> bark.v1alpha1.lifecycle.StopRequest
	6,  // 13: bark.v1alpha1.lifecycle.LifecycleService.Restart:input_type -> bark.v1alpha1.lifecycle.RestartRequest
	8,  // 14: bark.v1alpha1.lifecycle.LifecycleService.GetStatus:input_type -> bark.v1alpha1.lifecycle.GetStatusRequest
	5,  // 15: bark.v1alpha1.lifecycle.LifecycleService.Stop:output_type -> bark.v1alpha1.lifecycle.StopResponse
	7,  // 16: bark.v1alpha1.lifecycle.LifecycleService.Restart:output_type -> bark.v1alpha1.lifecycle.RestartResponse
	9,  // 17: bark.v1alpha1.lifecycle.LifecycleService.GetStatus:output_type -> bark.v1alpha1.lifecycle.GetStatusResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1alpha1_lifecycle_lifecycle_proto_init() }
func file_v1alpha1_lifecycle_lifecycle_proto_init() {
	if File_v1alpha1_lifecycle_lifecycle_proto != nil {
		return
	}
	file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[4].OneofWrappers = []any{}
	file_v1alpha1_lifecycle_lifecycle_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_lifecycle_lifecycle_proto_rawDesc), len(file_v1alpha1_lifecycle_lifecycle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_lifecycle_lifecycle_proto_goTypes,
		DependencyIndexes: file_v1alpha1_lifecycle_lifecycle_proto_depIdxs,
		EnumInfos:         file_v1alpha1_lifecycle_lifecycle_proto_enumTypes,
		MessageInfos:      file_v1alpha1_lifecycle_lifecycle_proto_msgTypes,
	}.Build()
	File_v1alpha1_lifecycle_lifecycle_proto = out.File
	file_v1alpha1_lifecycle_lifecycle_proto_goTypes = nil
	file_v1alpha1_lifecycle_lifecycle_proto_depIdxs = nil
}
