// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1alpha1/database/database.proto

package databasev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	database "github.com/blinklabs-io/bark/proto/v1alpha1/database"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "bark.v1alpha1.database.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceCreateSnapshotProcedure is the fully-qualified name of the DatabaseService's
	// CreateSnapshot RPC.
	DatabaseServiceCreateSnapshotProcedure = "/bark.v1alpha1.database.DatabaseService/CreateSnapshot"
	// DatabaseServiceGetSnapshotStatusProcedure is the fully-qualified name of the DatabaseService's
	// GetSnapshotStatus RPC.
	DatabaseServiceGetSnapshotStatusProcedure = "/bark.v1alpha1.database.DatabaseService/GetSnapshotStatus"
	// DatabaseServiceListSnapshotsProcedure is the fully-qualified name of the DatabaseService's
	// ListSnapshots RPC.
	DatabaseServiceListSnapshotsProcedure = "/bark.v1alpha1.database.DatabaseService/ListSnapshots"
	// DatabaseServiceDeleteSnapshotProcedure is the fully-qualified name of the DatabaseService's
	// DeleteSnapshot RPC.
	DatabaseServiceDeleteSnapshotProcedure = "/bark.v1alpha1.database.DatabaseService/DeleteSnapshot"
	// DatabaseServiceVerifySnapshotProcedure is the fully-qualified name of the DatabaseService's
	// VerifySnapshot RPC.
	DatabaseServiceVerifySnapshotProcedure = "/bark.v1alpha1.database.DatabaseService/VerifySnapshot"
	// DatabaseServiceRestoreProcedure is the fully-qualified name of the DatabaseService's Restore RPC.
	DatabaseServiceRestoreProcedure = "/bark.v1alpha1.database.DatabaseService/Restore"
	// DatabaseServiceGetRestoreStatusProcedure is the fully-qualified name of the DatabaseService's
	// GetRestoreStatus RPC.
	DatabaseServiceGetRestoreStatusProcedure = "/bark.v1alpha1.database.DatabaseService/GetRestoreStatus"
	// DatabaseServiceListAvailableSnapshotsProcedure is the fully-qualified name of the
	// DatabaseService's ListAvailableSnapshots RPC.
	DatabaseServiceListAvailableSnapshotsProcedure = "/bark.v1alpha1.database.DatabaseService/ListAvailableSnapshots"
	// DatabaseServiceTruncateProcedure is the fully-qualified name of the DatabaseService's Truncate
	// RPC.
	DatabaseServiceTruncateProcedure = "/bark.v1alpha1.database.DatabaseService/Truncate"
	// DatabaseServiceGetTruncateStatusProcedure is the fully-qualified name of the DatabaseService's
	// GetTruncateStatus RPC.
	DatabaseServiceGetTruncateStatusProcedure = "/bark.v1alpha1.database.DatabaseService/GetTruncateStatus"
	// DatabaseServiceStreamOperationProgressProcedure is the fully-qualified name of the
	// DatabaseService's StreamOperationProgress RPC.
	DatabaseServiceStreamOperationProgressProcedure = "/bark.v1alpha1.database.DatabaseService/StreamOperationProgress"
	// DatabaseServiceGetOperationHistoryProcedure is the fully-qualified name of the DatabaseService's
	// GetOperationHistory RPC.
	DatabaseServiceGetOperationHistoryProcedure = "/bark.v1alpha1.database.DatabaseService/GetOperationHistory"
	// DatabaseServiceGetDatabaseInfoProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseInfo RPC.
	DatabaseServiceGetDatabaseInfoProcedure = "/bark.v1alpha1.database.DatabaseService/GetDatabaseInfo"
	// DatabaseServiceCancelOperationProcedure is the fully-qualified name of the DatabaseService's
	// CancelOperation RPC.
	DatabaseServiceCancelOperationProcedure = "/bark.v1alpha1.database.DatabaseService/CancelOperation"
)

// DatabaseServiceClient is a client for the bark.v1alpha1.database.DatabaseService service.
type DatabaseServiceClient interface {
	// CreateSnapshot begins an async snapshot of the current database state.
	CreateSnapshot(context.Context, *connect.Request[database.CreateSnapshotRequest]) (*connect.Response[database.CreateSnapshotResponse], error)
	// GetSnapshotStatus returns the progress of a snapshot operation.
	GetSnapshotStatus(context.Context, *connect.Request[database.GetSnapshotStatusRequest]) (*connect.Response[database.GetSnapshotStatusResponse], error)
	// ListSnapshots returns all stored snapshots.
	ListSnapshots(context.Context, *connect.Request[database.ListSnapshotsRequest]) (*connect.Response[database.ListSnapshotsResponse], error)
	// DeleteSnapshot removes a stored snapshot.
	DeleteSnapshot(context.Context, *connect.Request[database.DeleteSnapshotRequest]) (*connect.Response[database.DeleteSnapshotResponse], error)
	// VerifySnapshot begins an async integrity check of a stored snapshot.
	VerifySnapshot(context.Context, *connect.Request[database.VerifySnapshotRequest]) (*connect.Response[database.VerifySnapshotResponse], error)
	// Restore begins an async restoration of the database from a snapshot.
	Restore(context.Context, *connect.Request[database.RestoreRequest]) (*connect.Response[database.RestoreResponse], error)
	// GetRestoreStatus returns the progress of a restore operation.
	GetRestoreStatus(context.Context, *connect.Request[database.GetRestoreStatusRequest]) (*connect.Response[database.GetRestoreStatusResponse], error)
	// ListAvailableSnapshots returns snapshots eligible for restoration,
	// including those on remote object storage.
	ListAvailableSnapshots(context.Context, *connect.Request[database.ListAvailableSnapshotsRequest]) (*connect.Response[database.ListAvailableSnapshotsResponse], error)
	// Truncate begins an async truncation of the chain. The target block is
	// preserved and becomes the new chain tip; only blocks with a strictly
	// greater slot or block number are removed.
	Truncate(context.Context, *connect.Request[database.TruncateRequest]) (*connect.Response[database.TruncateResponse], error)
	// GetTruncateStatus returns the progress of a truncate operation.
	GetTruncateStatus(context.Context, *connect.Request[database.GetTruncateStatusRequest]) (*connect.Response[database.GetTruncateStatusResponse], error)
	// StreamOperationProgress streams live progress updates for a running
	// operation until it completes or is cancelled.
	StreamOperationProgress(context.Context, *connect.Request[database.StreamOperationProgressRequest]) (*connect.ServerStreamForClient[database.StreamOperationProgressResponse], error)
	// GetOperationHistory returns a log of past operations.
	GetOperationHistory(context.Context, *connect.Request[database.GetOperationHistoryRequest]) (*connect.Response[database.GetOperationHistoryResponse], error)
	// GetDatabaseInfo returns current database metrics and state.
	GetDatabaseInfo(context.Context, *connect.Request[database.GetDatabaseInfoRequest]) (*connect.Response[database.GetDatabaseInfoResponse], error)
	// CancelOperation requests cancellation of a running operation.
	CancelOperation(context.Context, *connect.Request[database.CancelOperationRequest]) (*connect.Response[database.CancelOperationResponse], error)
}

// NewDatabaseServiceClient constructs a client for the bark.v1alpha1.database.DatabaseService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := database.File_v1alpha1_database_database_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		createSnapshot: connect.NewClient[database.CreateSnapshotRequest, database.CreateSnapshotResponse](
			httpClient,
			baseURL+DatabaseServiceCreateSnapshotProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateSnapshot")),
			connect.WithClientOptions(opts...),
		),
		getSnapshotStatus: connect.NewClient[database.GetSnapshotStatusRequest, database.GetSnapshotStatusResponse](
			httpClient,
			baseURL+DatabaseServiceGetSnapshotStatusProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetSnapshotStatus")),
			connect.WithClientOptions(opts...),
		),
		listSnapshots: connect.NewClient[database.ListSnapshotsRequest, database.ListSnapshotsResponse](
			httpClient,
			baseURL+DatabaseServiceListSnapshotsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListSnapshots")),
			connect.WithClientOptions(opts...),
		),
		deleteSnapshot: connect.NewClient[database.DeleteSnapshotRequest, database.DeleteSnapshotResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteSnapshotProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteSnapshot")),
			connect.WithClientOptions(opts...),
		),
		verifySnapshot: connect.NewClient[database.VerifySnapshotRequest, database.VerifySnapshotResponse](
			httpClient,
			baseURL+DatabaseServiceVerifySnapshotProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("VerifySnapshot")),
			connect.WithClientOptions(opts...),
		),
		restore: connect.NewClient[database.RestoreRequest, database.RestoreResponse](
			httpClient,
			baseURL+DatabaseServiceRestoreProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Restore")),
			connect.WithClientOptions(opts...),
		),
		getRestoreStatus: connect.NewClient[database.GetRestoreStatusRequest, database.GetRestoreStatusResponse](
			httpClient,
			baseURL+DatabaseServiceGetRestoreStatusProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetRestoreStatus")),
			connect.WithClientOptions(opts...),
		),
		listAvailableSnapshots: connect.NewClient[database.ListAvailableSnapshotsRequest, database.ListAvailableSnapshotsResponse](
			httpClient,
			baseURL+DatabaseServiceListAvailableSnapshotsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListAvailableSnapshots")),
			connect.WithClientOptions(opts...),
		),
		truncate: connect.NewClient[database.TruncateRequest, database.TruncateResponse](
			httpClient,
			baseURL+DatabaseServiceTruncateProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Truncate")),
			connect.WithClientOptions(opts...),
		),
		getTruncateStatus: connect.NewClient[database.GetTruncateStatusRequest, database.GetTruncateStatusResponse](
			httpClient,
			baseURL+DatabaseServiceGetTruncateStatusProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTruncateStatus")),
			connect.WithClientOptions(opts...),
		),
		streamOperationProgress: connect.NewClient[database.StreamOperationProgressRequest, database.StreamOperationProgressResponse](
			httpClient,
			baseURL+DatabaseServiceStreamOperationProgressProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("StreamOperationProgress")),
			connect.WithClientOptions(opts...),
		),
		getOperationHistory: connect.NewClient[database.GetOperationHistoryRequest, database.GetOperationHistoryResponse](
			httpClient,
			baseURL+DatabaseServiceGetOperationHistoryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetOperationHistory")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseInfo: connect.NewClient[database.GetDatabaseInfoRequest, database.GetDatabaseInfoResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseInfoProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseInfo")),
			connect.WithClientOptions(opts...),
		),
		cancelOperation: connect.NewClient[database.CancelOperationRequest, database.CancelOperationResponse](
			httpClient,
			baseURL+DatabaseServiceCancelOperationProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CancelOperation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	createSnapshot          *connect.Client[database.CreateSnapshotRequest, database.CreateSnapshotResponse]
	getSnapshotStatus       *connect.Client[database.GetSnapshotStatusRequest, database.GetSnapshotStatusResponse]
	listSnapshots           *connect.Client[database.ListSnapshotsRequest, database.ListSnapshotsResponse]
	deleteSnapshot          *connect.Client[database.DeleteSnapshotRequest, database.DeleteSnapshotResponse]
	verifySnapshot          *connect.Client[database.VerifySnapshotRequest, database.VerifySnapshotResponse]
	restore                 *connect.Client[database.RestoreRequest, database.RestoreResponse]
	getRestoreStatus        *connect.Client[database.GetRestoreStatusRequest, database.GetRestoreStatusResponse]
	listAvailableSnapshots  *connect.Client[database.ListAvailableSnapshotsRequest, database.ListAvailableSnapshotsResponse]
	truncate                *connect.Client[database.TruncateRequest, database.TruncateResponse]
	getTruncateStatus       *connect.Client[database.GetTruncateStatusRequest, database.GetTruncateStatusResponse]
	streamOperationProgress *connect.Client[database.StreamOperationProgressRequest, database.StreamOperationProgressResponse]
	getOperationHistory     *connect.Client[database.GetOperationHistoryRequest, database.GetOperationHistoryResponse]
	getDatabaseInfo         *connect.Client[database.GetDatabaseInfoRequest, database.GetDatabaseInfoResponse]
	cancelOperation         *connect.Client[database.CancelOperationRequest, database.CancelOperationResponse]
}

// CreateSnapshot calls bark.v1alpha1.database.DatabaseService.CreateSnapshot.
func (c *databaseServiceClient) CreateSnapshot(ctx context.Context, req *connect.Request[database.CreateSnapshotRequest]) (*connect.Response[database.CreateSnapshotResponse], error) {
	return c.createSnapshot.CallUnary(ctx, req)
}

// GetSnapshotStatus calls bark.v1alpha1.database.DatabaseService.GetSnapshotStatus.
func (c *databaseServiceClient) GetSnapshotStatus(ctx context.Context, req *connect.Request[database.GetSnapshotStatusRequest]) (*connect.Response[database.GetSnapshotStatusResponse], error) {
	return c.getSnapshotStatus.CallUnary(ctx, req)
}

// ListSnapshots calls bark.v1alpha1.database.DatabaseService.ListSnapshots.
func (c *databaseServiceClient) ListSnapshots(ctx context.Context, req *connect.Request[database.ListSnapshotsRequest]) (*connect.Response[database.ListSnapshotsResponse], error) {
	return c.listSnapshots.CallUnary(ctx, req)
}

// DeleteSnapshot calls bark.v1alpha1.database.DatabaseService.DeleteSnapshot.
func (c *databaseServiceClient) DeleteSnapshot(ctx context.Context, req *connect.Request[database.DeleteSnapshotRequest]) (*connect.Response[database.DeleteSnapshotResponse], error) {
	return c.deleteSnapshot.CallUnary(ctx, req)
}

// VerifySnapshot calls bark.v1alpha1.database.DatabaseService.VerifySnapshot.
func (c *databaseServiceClient) VerifySnapshot(ctx context.Context, req *connect.Request[database.VerifySnapshotRequest]) (*connect.Response[database.VerifySnapshotResponse], error) {
	return c.verifySnapshot.CallUnary(ctx, req)
}

// Restore calls bark.v1alpha1.database.DatabaseService.Restore.
func (c *databaseServiceClient) Restore(ctx context.Context, req *connect.Request[database.RestoreRequest]) (*connect.Response[database.RestoreResponse], error) {
	return c.restore.CallUnary(ctx, req)
}

// GetRestoreStatus calls bark.v1alpha1.database.DatabaseService.GetRestoreStatus.
func (c *databaseServiceClient) GetRestoreStatus(ctx context.Context, req *connect.Request[database.GetRestoreStatusRequest]) (*connect.Response[database.GetRestoreStatusResponse], error) {
	return c.getRestoreStatus.CallUnary(ctx, req)
}

// ListAvailableSnapshots calls bark.v1alpha1.database.DatabaseService.ListAvailableSnapshots.
func (c *databaseServiceClient) ListAvailableSnapshots(ctx context.Context, req *connect.Request[database.ListAvailableSnapshotsRequest]) (*connect.Response[database.ListAvailableSnapshotsResponse], error) {
	return c.listAvailableSnapshots.CallUnary(ctx, req)
}

// Truncate calls bark.v1alpha1.database.DatabaseService.Truncate.
func (c *databaseServiceClient) Truncate(ctx context.Context, req *connect.Request[database.TruncateRequest]) (*connect.Response[database.TruncateResponse], error) {
	return c.truncate.CallUnary(ctx, req)
}

// GetTruncateStatus calls bark.v1alpha1.database.DatabaseService.GetTruncateStatus.
func (c *databaseServiceClient) GetTruncateStatus(ctx context.Context, req *connect.Request[database.GetTruncateStatusRequest]) (*connect.Response[database.GetTruncateStatusResponse], error) {
	return c.getTruncateStatus.CallUnary(ctx, req)
}

// StreamOperationProgress calls bark.v1alpha1.database.DatabaseService.StreamOperationProgress.
func (c *databaseServiceClient) StreamOperationProgress(ctx context.Context, req *connect.Request[database.StreamOperationProgressRequest]) (*connect.ServerStreamForClient[database.StreamOperationProgressResponse], error) {
	return c.streamOperationProgress.CallServerStream(ctx, req)
}

// GetOperationHistory calls bark.v1alpha1.database.DatabaseService.GetOperationHistory.
func (c *databaseServiceClient) GetOperationHistory(ctx context.Context, req *connect.Request[database.GetOperationHistoryRequest]) (*connect.Response[database.GetOperationHistoryResponse], error) {
	return c.getOperationHistory.CallUnary(ctx, req)
}

// GetDatabaseInfo calls bark.v1alpha1.database.DatabaseService.GetDatabaseInfo.
func (c *databaseServiceClient) GetDatabaseInfo(ctx context.Context, req *connect.Request[database.GetDatabaseInfoRequest]) (*connect.Response[database.GetDatabaseInfoResponse], error) {
	return c.getDatabaseInfo.CallUnary(ctx, req)
}

// CancelOperation calls bark.v1alpha1.database.DatabaseService.CancelOperation.
func (c *databaseServiceClient) CancelOperation(ctx context.Context, req *connect.Request[database.CancelOperationRequest]) (*connect.Response[database.CancelOperationResponse], error) {
	return c.cancelOperation.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the bark.v1alpha1.database.DatabaseService
// service.
type DatabaseServiceHandler interface {
	// CreateSnapshot begins an async snapshot of the current database state.
	CreateSnapshot(context.Context, *connect.Request[database.CreateSnapshotRequest]) (*connect.Response[database.CreateSnapshotResponse], error)
	// GetSnapshotStatus returns the progress of a snapshot operation.
	GetSnapshotStatus(context.Context, *connect.Request[database.GetSnapshotStatusRequest]) (*connect.Response[database.GetSnapshotStatusResponse], error)
	// ListSnapshots returns all stored snapshots.
	ListSnapshots(context.Context, *connect.Request[database.ListSnapshotsRequest]) (*connect.Response[database.ListSnapshotsResponse], error)
	// DeleteSnapshot removes a stored snapshot.
	DeleteSnapshot(context.Context, *connect.Request[database.DeleteSnapshotRequest]) (*connect.Response[database.DeleteSnapshotResponse], error)
	// VerifySnapshot begins an async integrity check of a stored snapshot.
	VerifySnapshot(context.Context, *connect.Request[database.VerifySnapshotRequest]) (*connect.Response[database.VerifySnapshotResponse], error)
	// Restore begins an async restoration of the database from a snapshot.
	Restore(context.Context, *connect.Request[database.RestoreRequest]) (*connect.Response[database.RestoreResponse], error)
	// GetRestoreStatus returns the progress of a restore operation.
	GetRestoreStatus(context.Context, *connect.Request[database.GetRestoreStatusRequest]) (*connect.Response[database.GetRestoreStatusResponse], error)
	// ListAvailableSnapshots returns snapshots eligible for restoration,
	// including those on remote object storage.
	ListAvailableSnapshots(context.Context, *connect.Request[database.ListAvailableSnapshotsRequest]) (*connect.Response[database.ListAvailableSnapshotsResponse], error)
	// Truncate begins an async truncation of the chain. The target block is
	// preserved and becomes the new chain tip; only blocks with a strictly
	// greater slot or block number are removed.
	Truncate(context.Context, *connect.Request[database.TruncateRequest]) (*connect.Response[database.TruncateResponse], error)
	// GetTruncateStatus returns the progress of a truncate operation.
	GetTruncateStatus(context.Context, *connect.Request[database.GetTruncateStatusRequest]) (*connect.Response[database.GetTruncateStatusResponse], error)
	// StreamOperationProgress streams live progress updates for a running
	// operation until it completes or is cancelled.
	StreamOperationProgress(context.Context, *connect.Request[database.StreamOperationProgressRequest], *connect.ServerStream[database.StreamOperationProgressResponse]) error
	// GetOperationHistory returns a log of past operations.
	GetOperationHistory(context.Context, *connect.Request[database.GetOperationHistoryRequest]) (*connect.Response[database.GetOperationHistoryResponse], error)
	// GetDatabaseInfo returns current database metrics and state.
	GetDatabaseInfo(context.Context, *connect.Request[database.GetDatabaseInfoRequest]) (*connect.Response[database.GetDatabaseInfoResponse], error)
	// CancelOperation requests cancellation of a running operation.
	CancelOperation(context.Context, *connect.Request[database.CancelOperationRequest]) (*connect.Response[database.CancelOperationResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := database.File_v1alpha1_database_database_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceCreateSnapshotHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateSnapshotProcedure,
		svc.CreateSnapshot,
		connect.WithSchema(databaseServiceMethods.ByName("CreateSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetSnapshotStatusHandler := connect.NewUnaryHandler(
		DatabaseServiceGetSnapshotStatusProcedure,
		svc.GetSnapshotStatus,
		connect.WithSchema(databaseServiceMethods.ByName("GetSnapshotStatus")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListSnapshotsHandler := connect.NewUnaryHandler(
		DatabaseServiceListSnapshotsProcedure,
		svc.ListSnapshots,
		connect.WithSchema(databaseServiceMethods.ByName("ListSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteSnapshotHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteSnapshotProcedure,
		svc.DeleteSnapshot,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceVerifySnapshotHandler := connect.NewUnaryHandler(
		DatabaseServiceVerifySnapshotProcedure,
		svc.VerifySnapshot,
		connect.WithSchema(databaseServiceMethods.ByName("VerifySnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRestoreHandler := connect.NewUnaryHandler(
		DatabaseServiceRestoreProcedure,
		svc.Restore,
		connect.WithSchema(databaseServiceMethods.ByName("Restore")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetRestoreStatusHandler := connect.NewUnaryHandler(
		DatabaseServiceGetRestoreStatusProcedure,
		svc.GetRestoreStatus,
		connect.WithSchema(databaseServiceMethods.ByName("GetRestoreStatus")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListAvailableSnapshotsHandler := connect.NewUnaryHandler(
		DatabaseServiceListAvailableSnapshotsProcedure,
		svc.ListAvailableSnapshots,
		connect.WithSchema(databaseServiceMethods.ByName("ListAvailableSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTruncateHandler := connect.NewUnaryHandler(
		DatabaseServiceTruncateProcedure,
		svc.Truncate,
		connect.WithSchema(databaseServiceMethods.ByName("Truncate")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTruncateStatusHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTruncateStatusProcedure,
		svc.GetTruncateStatus,
		connect.WithSchema(databaseServiceMethods.ByName("GetTruncateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceStreamOperationProgressHandler := connect.NewServerStreamHandler(
		DatabaseServiceStreamOperationProgressProcedure,
		svc.StreamOperationProgress,
		connect.WithSchema(databaseServiceMethods.ByName("StreamOperationProgress")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetOperationHistoryHandler := connect.NewUnaryHandler(
		DatabaseServiceGetOperationHistoryProcedure,
		svc.GetOperationHistory,
		connect.WithSchema(databaseServiceMethods.ByName("GetOperationHistory")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseInfoHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseInfoProcedure,
		svc.GetDatabaseInfo,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseInfo")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCancelOperationHandler := connect.NewUnaryHandler(
		DatabaseServiceCancelOperationProcedure,
		svc.CancelOperation,
		connect.WithSchema(databaseServiceMethods.ByName("CancelOperation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bark.v1alpha1.database.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceCreateSnapshotProcedure:
			databaseServiceCreateSnapshotHandler.ServeHTTP(w, r)
		case DatabaseServiceGetSnapshotStatusProcedure:
			databaseServiceGetSnapshotStatusHandler.ServeHTTP(w, r)
		case DatabaseServiceListSnapshotsProcedure:
			databaseServiceListSnapshotsHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteSnapshotProcedure:
			databaseServiceDeleteSnapshotHandler.ServeHTTP(w, r)
		case DatabaseServiceVerifySnapshotProcedure:
			databaseServiceVerifySnapshotHandler.ServeHTTP(w, r)
		case DatabaseServiceRestoreProcedure:
			databaseServiceRestoreHandler.ServeHTTP(w, r)
		case DatabaseServiceGetRestoreStatusProcedure:
			databaseServiceGetRestoreStatusHandler.ServeHTTP(w, r)
		case DatabaseServiceListAvailableSnapshotsProcedure:
			databaseServiceListAvailableSnapshotsHandler.ServeHTTP(w, r)
		case DatabaseServiceTruncateProcedure:
			databaseServiceTruncateHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTruncateStatusProcedure:
			databaseServiceGetTruncateStatusHandler.ServeHTTP(w, r)
		case DatabaseServiceStreamOperationProgressProcedure:
			databaseServiceStreamOperationProgressHandler.ServeHTTP(w, r)
		case DatabaseServiceGetOperationHistoryProcedure:
			databaseServiceGetOperationHistoryHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseInfoProcedure:
			databaseServiceGetDatabaseInfoHandler.ServeHTTP(w, r)
		case DatabaseServiceCancelOperationProcedure:
			databaseServiceCancelOperationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) CreateSnapshot(context.Context, *connect.Request[database.CreateSnapshotRequest]) (*connect.Response[database.CreateSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.CreateSnapshot is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetSnapshotStatus(context.Context, *connect.Request[database.GetSnapshotStatusRequest]) (*connect.Response[database.GetSnapshotStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.GetSnapshotStatus is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListSnapshots(context.Context, *connect.Request[database.ListSnapshotsRequest]) (*connect.Response[database.ListSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.ListSnapshots is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteSnapshot(context.Context, *connect.Request[database.DeleteSnapshotRequest]) (*connect.Response[database.DeleteSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.DeleteSnapshot is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) VerifySnapshot(context.Context, *connect.Request[database.VerifySnapshotRequest]) (*connect.Response[database.VerifySnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.VerifySnapshot is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Restore(context.Context, *connect.Request[database.RestoreRequest]) (*connect.Response[database.RestoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.Restore is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetRestoreStatus(context.Context, *connect.Request[database.GetRestoreStatusRequest]) (*connect.Response[database.GetRestoreStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.GetRestoreStatus is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListAvailableSnapshots(context.Context, *connect.Request[database.ListAvailableSnapshotsRequest]) (*connect.Response[database.ListAvailableSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.ListAvailableSnapshots is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Truncate(context.Context, *connect.Request[database.TruncateRequest]) (*connect.Response[database.TruncateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.Truncate is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTruncateStatus(context.Context, *connect.Request[database.GetTruncateStatusRequest]) (*connect.Response[database.GetTruncateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.GetTruncateStatus is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) StreamOperationProgress(context.Context, *connect.Request[database.StreamOperationProgressRequest], *connect.ServerStream[database.StreamOperationProgressResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.StreamOperationProgress is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetOperationHistory(context.Context, *connect.Request[database.GetOperationHistoryRequest]) (*connect.Response[database.GetOperationHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.GetOperationHistory is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseInfo(context.Context, *connect.Request[database.GetDatabaseInfoRequest]) (*connect.Response[database.GetDatabaseInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.GetDatabaseInfo is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CancelOperation(context.Context, *connect.Request[database.CancelOperationRequest]) (*connect.Response[database.CancelOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.database.DatabaseService.CancelOperation is not implemented"))
}
