// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1alpha1/lifecycle/lifecycle.proto

package lifecyclev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	lifecycle "github.com/blinklabs-io/bark/proto/v1alpha1/lifecycle"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LifecycleServiceName is the fully-qualified name of the LifecycleService service.
	LifecycleServiceName = "bark.v1alpha1.lifecycle.LifecycleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LifecycleServiceStopProcedure is the fully-qualified name of the LifecycleService's Stop RPC.
	LifecycleServiceStopProcedure = "/bark.v1alpha1.lifecycle.LifecycleService/Stop"
	// LifecycleServiceRestartProcedure is the fully-qualified name of the LifecycleService's Restart
	// RPC.
	LifecycleServiceRestartProcedure = "/bark.v1alpha1.lifecycle.LifecycleService/Restart"
	// LifecycleServiceGetStatusProcedure is the fully-qualified name of the LifecycleService's
	// GetStatus RPC.
	LifecycleServiceGetStatusProcedure = "/bark.v1alpha1.lifecycle.LifecycleService/GetStatus"
)

// LifecycleServiceClient is a client for the bark.v1alpha1.lifecycle.LifecycleService service.
type LifecycleServiceClient interface {
	// Stop initiates a graceful shutdown of the node: the shutdown
	// coordinator ceases chain sync, drains in-flight connections, flushes
	// the database, and then exits the process. If the graceful sequence
	// does not finish within the effective timeout, the coordinator forces
	// the process to exit rather than hang.
	Stop(context.Context, *connect.Request[lifecycle.StopRequest]) (*connect.Response[lifecycle.StopResponse], error)
	// Restart performs the same graceful shutdown sequence as Stop and then
	// re-executes the node process in place (same binary path and
	// arguments), rather than leaving it stopped. This allows picking up a
	// replaced binary (e.g. after an upgrade) or a changed configuration.
	Restart(context.Context, *connect.Request[lifecycle.RestartRequest]) (*connect.Response[lifecycle.RestartResponse], error)
	// GetStatus reports the node's current lifecycle state, health, uptime,
	// version, and chain synchronization state. It remains available while
	// a graceful stop or restart is draining, so callers can poll it to
	// observe the transition and the enforced deadline.
	GetStatus(context.Context, *connect.Request[lifecycle.GetStatusRequest]) (*connect.Response[lifecycle.GetStatusResponse], error)
}

// NewLifecycleServiceClient constructs a client for the bark.v1alpha1.lifecycle.LifecycleService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLifecycleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LifecycleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lifecycleServiceMethods := lifecycle.File_v1alpha1_lifecycle_lifecycle_proto.Services().ByName("LifecycleService").Methods()
	return &lifecycleServiceClient{
		stop: connect.NewClient[lifecycle.StopRequest, lifecycle.StopResponse](
			httpClient,
			baseURL+LifecycleServiceStopProcedure,
			connect.WithSchema(lifecycleServiceMethods.ByName("Stop")),
			connect.WithClientOptions(opts...),
		),
		restart: connect.NewClient[lifecycle.RestartRequest, lifecycle.RestartResponse](
			httpClient,
			baseURL+LifecycleServiceRestartProcedure,
			connect.WithSchema(lifecycleServiceMethods.ByName("Restart")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[lifecycle.GetStatusRequest, lifecycle.GetStatusResponse](
			httpClient,
			baseURL+LifecycleServiceGetStatusProcedure,
			connect.WithSchema(lifecycleServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lifecycleServiceClient implements LifecycleServiceClient.
type lifecycleServiceClient struct {
	stop      *connect.Client[lifecycle.StopRequest, lifecycle.StopResponse]
	restart   *connect.Client[lifecycle.RestartRequest, lifecycle.RestartResponse]
	getStatus *connect.Client[lifecycle.GetStatusRequest, lifecycle.GetStatusResponse]
}

// Stop calls bark.v1alpha1.lifecycle.LifecycleService.Stop.
func (c *lifecycleServiceClient) Stop(ctx context.Context, req *connect.Request[lifecycle.StopRequest]) (*connect.Response[lifecycle.StopResponse], error) {
	return c.stop.CallUnary(ctx, req)
}

// Restart calls bark.v1alpha1.lifecycle.LifecycleService.Restart.
func (c *lifecycleServiceClient) Restart(ctx context.Context, req *connect.Request[lifecycle.RestartRequest]) (*connect.Response[lifecycle.RestartResponse], error) {
	return c.restart.CallUnary(ctx, req)
}

// GetStatus calls bark.v1alpha1.lifecycle.LifecycleService.GetStatus.
func (c *lifecycleServiceClient) GetStatus(ctx context.Context, req *connect.Request[lifecycle.GetStatusRequest]) (*connect.Response[lifecycle.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// LifecycleServiceHandler is an implementation of the bark.v1alpha1.lifecycle.LifecycleService
// service.
type LifecycleServiceHandler interface {
	// Stop initiates a graceful shutdown of the node: the shutdown
	// coordinator ceases chain sync, drains in-flight connections, flushes
	// the database, and then exits the process. If the graceful sequence
	// does not finish within the effective timeout, the coordinator forces
	// the process to exit rather than hang.
	Stop(context.Context, *connect.Request[lifecycle.StopRequest]) (*connect.Response[lifecycle.StopResponse], error)
	// Restart performs the same graceful shutdown sequence as Stop and then
	// re-executes the node process in place (same binary path and
	// arguments), rather than leaving it stopped. This allows picking up a
	// replaced binary (e.g. after an upgrade) or a changed configuration.
	Restart(context.Context, *connect.Request[lifecycle.RestartRequest]) (*connect.Response[lifecycle.RestartResponse], error)
	// GetStatus reports the node's current lifecycle state, health, uptime,
	// version, and chain synchronization state. It remains available while
	// a graceful stop or restart is draining, so callers can poll it to
	// observe the transition and the enforced deadline.
	GetStatus(context.Context, *connect.Request[lifecycle.GetStatusRequest]) (*connect.Response[lifecycle.GetStatusResponse], error)
}

// NewLifecycleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLifecycleServiceHandler(svc LifecycleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lifecycleServiceMethods := lifecycle.File_v1alpha1_lifecycle_lifecycle_proto.Services().ByName("LifecycleService").Methods()
	lifecycleServiceStopHandler := connect.NewUnaryHandler(
		LifecycleServiceStopProcedure,
		svc.Stop,
		connect.WithSchema(lifecycleServiceMethods.ByName("Stop")),
		connect.WithHandlerOptions(opts...),
	)
	lifecycleServiceRestartHandler := connect.NewUnaryHandler(
		LifecycleServiceRestartProcedure,
		svc.Restart,
		connect.WithSchema(lifecycleServiceMethods.ByName("Restart")),
		connect.WithHandlerOptions(opts...),
	)
	lifecycleServiceGetStatusHandler := connect.NewUnaryHandler(
		LifecycleServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(lifecycleServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bark.v1alpha1.lifecycle.LifecycleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LifecycleServiceStopProcedure:
			lifecycleServiceStopHandler.ServeHTTP(w, r)
		case LifecycleServiceRestartProcedure:
			lifecycleServiceRestartHandler.ServeHTTP(w, r)
		case LifecycleServiceGetStatusProcedure:
			lifecycleServiceGetStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLifecycleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLifecycleServiceHandler struct{}

func (UnimplementedLifecycleServiceHandler) Stop(context.Context, *connect.Request[lifecycle.StopRequest]) (*connect.Response[lifecycle.StopResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.lifecycle.LifecycleService.Stop is not implemented"))
}

func (UnimplementedLifecycleServiceHandler) Restart(context.Context, *connect.Request[lifecycle.RestartRequest]) (*connect.Response[lifecycle.RestartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.lifecycle.LifecycleService.Restart is not implemented"))
}

func (UnimplementedLifecycleServiceHandler) GetStatus(context.Context, *connect.Request[lifecycle.GetStatusRequest]) (*connect.Response[lifecycle.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.lifecycle.LifecycleService.GetStatus is not implemented"))
}
