// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1alpha1/archive/archive.proto

package archiveconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	archive "github.com/blinklabs-io/bark/v1alpha1/archive"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArchiveServiceName is the fully-qualified name of the ArchiveService service.
	ArchiveServiceName = "bark.v1alpha1.archive.ArchiveService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArchiveServiceFetchBlockProcedure is the fully-qualified name of the ArchiveService's FetchBlock
	// RPC.
	ArchiveServiceFetchBlockProcedure = "/bark.v1alpha1.archive.ArchiveService/FetchBlock"
)

// ArchiveServiceClient is a client for the bark.v1alpha1.archive.ArchiveService service.
type ArchiveServiceClient interface {
	// FetchBlock retrieves signed URLs for one or more blocks.
	// The client can then use these URLs to directly download the block data from cloud storage.
	FetchBlock(context.Context, *connect.Request[archive.FetchBlockRequest]) (*connect.Response[archive.FetchBlockResponse], error)
}

// NewArchiveServiceClient constructs a client for the bark.v1alpha1.archive.ArchiveService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArchiveServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArchiveServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	archiveServiceMethods := archive.File_v1alpha1_archive_archive_proto.Services().ByName("ArchiveService").Methods()
	return &archiveServiceClient{
		fetchBlock: connect.NewClient[archive.FetchBlockRequest, archive.FetchBlockResponse](
			httpClient,
			baseURL+ArchiveServiceFetchBlockProcedure,
			connect.WithSchema(archiveServiceMethods.ByName("FetchBlock")),
			connect.WithClientOptions(opts...),
		),
	}
}

// archiveServiceClient implements ArchiveServiceClient.
type archiveServiceClient struct {
	fetchBlock *connect.Client[archive.FetchBlockRequest, archive.FetchBlockResponse]
}

// FetchBlock calls bark.v1alpha1.archive.ArchiveService.FetchBlock.
func (c *archiveServiceClient) FetchBlock(ctx context.Context, req *connect.Request[archive.FetchBlockRequest]) (*connect.Response[archive.FetchBlockResponse], error) {
	return c.fetchBlock.CallUnary(ctx, req)
}

// ArchiveServiceHandler is an implementation of the bark.v1alpha1.archive.ArchiveService service.
type ArchiveServiceHandler interface {
	// FetchBlock retrieves signed URLs for one or more blocks.
	// The client can then use these URLs to directly download the block data from cloud storage.
	FetchBlock(context.Context, *connect.Request[archive.FetchBlockRequest]) (*connect.Response[archive.FetchBlockResponse], error)
}

// NewArchiveServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArchiveServiceHandler(svc ArchiveServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	archiveServiceMethods := archive.File_v1alpha1_archive_archive_proto.Services().ByName("ArchiveService").Methods()
	archiveServiceFetchBlockHandler := connect.NewUnaryHandler(
		ArchiveServiceFetchBlockProcedure,
		svc.FetchBlock,
		connect.WithSchema(archiveServiceMethods.ByName("FetchBlock")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bark.v1alpha1.archive.ArchiveService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArchiveServiceFetchBlockProcedure:
			archiveServiceFetchBlockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArchiveServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArchiveServiceHandler struct{}

func (UnimplementedArchiveServiceHandler) FetchBlock(context.Context, *connect.Request[archive.FetchBlockRequest]) (*connect.Response[archive.FetchBlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bark.v1alpha1.archive.ArchiveService.FetchBlock is not implemented"))
}
