// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1alpha1/database/database.proto

package databasev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationStatus describes the lifecycle state of an async operation.
type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_RUNNING     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_COMPLETED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
	OperationStatus_OPERATION_STATUS_CANCELLED   OperationStatus = 5
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_RUNNING",
		3: "OPERATION_STATUS_COMPLETED",
		4: "OPERATION_STATUS_FAILED",
		5: "OPERATION_STATUS_CANCELLED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_RUNNING":     2,
		"OPERATION_STATUS_COMPLETED":   3,
		"OPERATION_STATUS_FAILED":      4,
		"OPERATION_STATUS_CANCELLED":   5,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_database_database_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_database_database_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{0}
}

// OperationType identifies which kind of operation a record refers to.
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_SNAPSHOT    OperationType = 1
	OperationType_OPERATION_TYPE_RESTORE     OperationType = 2
	OperationType_OPERATION_TYPE_TRUNCATE    OperationType = 3
	OperationType_OPERATION_TYPE_VERIFY      OperationType = 4
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_SNAPSHOT",
		2: "OPERATION_TYPE_RESTORE",
		3: "OPERATION_TYPE_TRUNCATE",
		4: "OPERATION_TYPE_VERIFY",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_SNAPSHOT":    1,
		"OPERATION_TYPE_RESTORE":     2,
		"OPERATION_TYPE_TRUNCATE":    3,
		"OPERATION_TYPE_VERIFY":      4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_database_database_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_v1alpha1_database_database_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{1}
}

// BlockRef identifies a block by one or more of hash, slot, or block number.
// At least one field must be set. When multiple fields are set, all must
// agree; the server returns INVALID_ARGUMENT if they are inconsistent.
type BlockRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block hash as a hex-encoded string.
	Hash *string `protobuf:"bytes,1,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	// Slot number.
	Slot *uint64 `protobuf:"varint,2,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
	// Block number / height.
	BlockNumber   *uint64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRef) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *BlockRef) GetSlot() uint64 {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return 0
}

func (x *BlockRef) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

// OperationProgress reports the current state of an async operation.
type OperationProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique operation identifier.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Current lifecycle state.
	Status OperationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=bark.v1alpha1.database.OperationStatus" json:"status,omitempty"`
	// Completion percentage in [0.0, 100.0].
	ProgressPercent float32 `protobuf:"fixed32,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	// Human-readable status message.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// When the operation was created.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When this progress record was produced.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// When the operation reached a terminal state, if it has.
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProgress) Reset() {
	*x = OperationProgress{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProgress) ProtoMessage() {}

func (x *OperationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProgress.ProtoReflect.Descriptor instead.
func (*OperationProgress) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{1}
}

func (x *OperationProgress) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationProgress) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *OperationProgress) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *OperationProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *OperationProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OperationProgress) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// OperationRecord is a summary entry in the operation history log.
type OperationRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique operation identifier.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Kind of operation.
	Type OperationType `protobuf:"varint,2,opt,name=type,proto3,enum=bark.v1alpha1.database.OperationType" json:"type,omitempty"`
	// Terminal state of the operation.
	Status OperationStatus `protobuf:"varint,3,opt,name=status,proto3,enum=bark.v1alpha1.database.OperationStatus" json:"status,omitempty"`
	// Human-readable description or error message.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// When the operation started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the operation reached a terminal state.
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRecord) Reset() {
	*x = OperationRecord{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRecord) ProtoMessage() {}

func (x *OperationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRecord.ProtoReflect.Descriptor instead.
func (*OperationRecord) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{2}
}

func (x *OperationRecord) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRecord) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *OperationRecord) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *OperationRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationRecord) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *OperationRecord) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// SnapshotInfo describes a stored snapshot.
type SnapshotInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique snapshot identifier.
	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Human-readable name given at creation time.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Chain tip at the time the snapshot was taken.
	Tip *BlockRef `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"`
	// Total size in bytes.
	SizeBytes uint64 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Content checksum (format: "<algorithm>:<hex>", e.g. "sha256:abc123").
	Checksum string `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// When the snapshot was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Storage location of the snapshot (local path or remote URI).
	Location      string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotInfo) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SnapshotInfo) GetTip() *BlockRef {
	if x != nil {
		return x.Tip
	}
	return nil
}

func (x *SnapshotInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SnapshotInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SnapshotInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable label for this snapshot.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional free-form description.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSnapshotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for tracking this operation.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Identifier for the snapshot being created (available before completion).
	SnapshotId    string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSnapshotResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotStatusRequest) Reset() {
	*x = GetSnapshotStatusRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotStatusRequest) ProtoMessage() {}

func (x *GetSnapshotStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{6}
}

func (x *GetSnapshotStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetSnapshotStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current progress of the snapshot operation.
	Progress *OperationProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	// Snapshot identifier (populated once the snapshot is committed).
	SnapshotId    string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotStatusResponse) Reset() {
	*x = GetSnapshotStatusResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotStatusResponse) ProtoMessage() {}

func (x *GetSnapshotStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{7}
}

func (x *GetSnapshotStatusResponse) GetProgress() *OperationProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetSnapshotStatusResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ListSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of results to return. 0 means server default.
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous response for pagination.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{8}
}

func (x *ListSnapshotsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSnapshotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSnapshotsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Snapshots []*SnapshotInfo        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	// Token to retrieve the next page, empty when no further pages exist.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{9}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListSnapshotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the snapshot was removed.
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSnapshotResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type VerifySnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySnapshotRequest) Reset() {
	*x = VerifySnapshotRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySnapshotRequest) ProtoMessage() {}

func (x *VerifySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySnapshotRequest.ProtoReflect.Descriptor instead.
func (*VerifySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{12}
}

func (x *VerifySnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type VerifySnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for tracking this verify operation.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySnapshotResponse) Reset() {
	*x = VerifySnapshotResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySnapshotResponse) ProtoMessage() {}

func (x *VerifySnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySnapshotResponse.ProtoReflect.Descriptor instead.
func (*VerifySnapshotResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{13}
}

func (x *VerifySnapshotResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot to restore from.
	SnapshotId    string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type RestoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for tracking this operation.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetRestoreStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestoreStatusRequest) Reset() {
	*x = GetRestoreStatusRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestoreStatusRequest) ProtoMessage() {}

func (x *GetRestoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestoreStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRestoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{16}
}

func (x *GetRestoreStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetRestoreStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *OperationProgress     `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestoreStatusResponse) Reset() {
	*x = GetRestoreStatusResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestoreStatusResponse) ProtoMessage() {}

func (x *GetRestoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestoreStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRestoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{17}
}

func (x *GetRestoreStatusResponse) GetProgress() *OperationProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ListAvailableSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of results to return. 0 means server default.
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous response for pagination.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableSnapshotsRequest) Reset() {
	*x = ListAvailableSnapshotsRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableSnapshotsRequest) ProtoMessage() {}

func (x *ListAvailableSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{18}
}

func (x *ListAvailableSnapshotsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAvailableSnapshotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAvailableSnapshotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Includes local snapshots and those discoverable on remote object storage.
	Snapshots     []*SnapshotInfo `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	NextPageToken string          `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableSnapshotsResponse) Reset() {
	*x = ListAvailableSnapshotsResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableSnapshotsResponse) ProtoMessage() {}

func (x *ListAvailableSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{19}
}

func (x *ListAvailableSnapshotsResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListAvailableSnapshotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TruncateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block to retain as the new chain tip. Blocks with a strictly greater
	// slot or block number are removed. At least one field of target must be set,
	// and hash, slot, and block_number must identify the same block when combined.
	Target        *BlockRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{20}
}

func (x *TruncateRequest) GetTarget() *BlockRef {
	if x != nil {
		return x.Target
	}
	return nil
}

type TruncateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for tracking this operation.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateResponse) Reset() {
	*x = TruncateResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateResponse) ProtoMessage() {}

func (x *TruncateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateResponse.ProtoReflect.Descriptor instead.
func (*TruncateResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{21}
}

func (x *TruncateResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetTruncateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruncateStatusRequest) Reset() {
	*x = GetTruncateStatusRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruncateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruncateStatusRequest) ProtoMessage() {}

func (x *GetTruncateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruncateStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTruncateStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{22}
}

func (x *GetTruncateStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetTruncateStatusResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Progress *OperationProgress     `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	// Number of blocks removed once the operation completes.
	BlocksRemoved uint64 `protobuf:"varint,2,opt,name=blocks_removed,json=blocksRemoved,proto3" json:"blocks_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruncateStatusResponse) Reset() {
	*x = GetTruncateStatusResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruncateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruncateStatusResponse) ProtoMessage() {}

func (x *GetTruncateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruncateStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTruncateStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{23}
}

func (x *GetTruncateStatusResponse) GetProgress() *OperationProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetTruncateStatusResponse) GetBlocksRemoved() uint64 {
	if x != nil {
		return x.BlocksRemoved
	}
	return 0
}

type StreamOperationProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOperationProgressRequest) Reset() {
	*x = StreamOperationProgressRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOperationProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOperationProgressRequest) ProtoMessage() {}

func (x *StreamOperationProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOperationProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamOperationProgressRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{24}
}

func (x *StreamOperationProgressRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type StreamOperationProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *OperationProgress     `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOperationProgressResponse) Reset() {
	*x = StreamOperationProgressResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOperationProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOperationProgressResponse) ProtoMessage() {}

func (x *StreamOperationProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOperationProgressResponse.ProtoReflect.Descriptor instead.
func (*StreamOperationProgressResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{25}
}

func (x *StreamOperationProgressResponse) GetProgress() *OperationProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetOperationHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by operation type. Omit to return all types.
	TypeFilter *OperationType `protobuf:"varint,1,opt,name=type_filter,json=typeFilter,proto3,enum=bark.v1alpha1.database.OperationType,oneof" json:"type_filter,omitempty"`
	// Filter by status. Omit to return all statuses.
	StatusFilter *OperationStatus `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=bark.v1alpha1.database.OperationStatus,oneof" json:"status_filter,omitempty"`
	// Maximum number of records to return. 0 means server default.
	PageSize uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous response for pagination.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationHistoryRequest) Reset() {
	*x = GetOperationHistoryRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationHistoryRequest) ProtoMessage() {}

func (x *GetOperationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOperationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{26}
}

func (x *GetOperationHistoryRequest) GetTypeFilter() OperationType {
	if x != nil && x.TypeFilter != nil {
		return *x.TypeFilter
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *GetOperationHistoryRequest) GetStatusFilter() OperationStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetOperationHistoryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetOperationHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetOperationHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*OperationRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationHistoryResponse) Reset() {
	*x = GetOperationHistoryResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationHistoryResponse) ProtoMessage() {}

func (x *GetOperationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetOperationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{27}
}

func (x *GetOperationHistoryResponse) GetRecords() []*OperationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetOperationHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDatabaseInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseInfoRequest) Reset() {
	*x = GetDatabaseInfoRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseInfoRequest) ProtoMessage() {}

func (x *GetDatabaseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{28}
}

type GetDatabaseInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current chain tip.
	Tip *BlockRef `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	// Total number of blocks stored.
	BlockCount uint64 `protobuf:"varint,2,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	// Total on-disk size in bytes across all storage backends.
	SizeBytes uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Slot of the oldest block retained.
	OldestSlot uint64 `protobuf:"varint,4,opt,name=oldest_slot,json=oldestSlot,proto3" json:"oldest_slot,omitempty"`
	// Whether a database operation is currently running.
	OperationInProgress bool `protobuf:"varint,5,opt,name=operation_in_progress,json=operationInProgress,proto3" json:"operation_in_progress,omitempty"`
	// Operation ID of any currently running operation.
	CurrentOperationId *string `protobuf:"bytes,6,opt,name=current_operation_id,json=currentOperationId,proto3,oneof" json:"current_operation_id,omitempty"`
	// Configured storage tier for the running node (e.g. "core", "api").
	Tier          string `protobuf:"bytes,7,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseInfoResponse) Reset() {
	*x = GetDatabaseInfoResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseInfoResponse) ProtoMessage() {}

func (x *GetDatabaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{29}
}

func (x *GetDatabaseInfoResponse) GetTip() *BlockRef {
	if x != nil {
		return x.Tip
	}
	return nil
}

func (x *GetDatabaseInfoResponse) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *GetDatabaseInfoResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetDatabaseInfoResponse) GetOldestSlot() uint64 {
	if x != nil {
		return x.OldestSlot
	}
	return 0
}

func (x *GetDatabaseInfoResponse) GetOperationInProgress() bool {
	if x != nil {
		return x.OperationInProgress
	}
	return false
}

func (x *GetDatabaseInfoResponse) GetCurrentOperationId() string {
	if x != nil && x.CurrentOperationId != nil {
		return *x.CurrentOperationId
	}
	return ""
}

func (x *GetDatabaseInfoResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{30}
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CancelOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the operation at the time the cancellation was accepted.
	Status        OperationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=bark.v1alpha1.database.OperationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationResponse) Reset() {
	*x = CancelOperationResponse{}
	mi := &file_v1alpha1_database_database_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationResponse) ProtoMessage() {}

func (x *CancelOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_database_database_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationResponse.ProtoReflect.Descriptor instead.
func (*CancelOperationResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_database_database_proto_rawDescGZIP(), []int{31}
}

func (x *CancelOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

var File_v1alpha1_database_database_proto protoreflect.FileDescriptor

const file_v1alpha1_database_database_proto_rawDesc = "" +
	"\n" +
	" v1alpha1/database/database.proto\x12\x16bark.v1alpha1.database\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\bBlockRef\x12\x17\n" +
	"\x04hash\x18\x01 \x01(\tH\x00R\x04hash\x88\x01\x01\x12\x17\n" +
	"\x04slot\x18\x02 \x01(\x04H\x01R\x04slot\x88\x01\x01\x12&\n" +
	"\fblock_number\x18\x03 \x01(\x04H\x02R\vblockNumber\x88\x01\x01B\a\n" +
	"\x05_hashB\a\n" +
	"\x05_slotB\x0f\n" +
	"\r_block_number\"\x87\x03\n" +
	"\x11OperationProgress\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.bark.v1alpha1.database.OperationStatusR\x06status\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x02R\x0fprogressPercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"\xda\x02\n" +
	"\x0fOperationRecord\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x129\n" +
	"\x04type\x18\x02 \x01(\x0e2%.bark.v1alpha1.database.OperationTypeR\x04type\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.bark.v1alpha1.database.OperationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"\xab\x02\n" +
	"\fSnapshotInfo\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x03tip\x18\x04 \x01(\v2 .bark.v1alpha1.database.BlockRefR\x03tip\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\"M\n" +
	"\x15CreateSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\\\n" +
	"\x16CreateSnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"=\n" +
	"\x18GetSnapshotStatusRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\x83\x01\n" +
	"\x19GetSnapshotStatusResponse\x12E\n" +
	"\bprogress\x18\x01 \x01(\v2).bark.v1alpha1.database.OperationProgressR\bprogress\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"R\n" +
	"\x14ListSnapshotsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x15ListSnapshotsResponse\x12B\n" +
	"\tsnapshots\x18\x01 \x03(\v2$.bark.v1alpha1.database.SnapshotInfoR\tsnapshots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"8\n" +
	"\x15DeleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"S\n" +
	"\x16DeleteSnapshotResponse\x129\n" +
	"\n" +
	"deleted_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"8\n" +
	"\x15VerifySnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\";\n" +
	"\x16VerifySnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"1\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"4\n" +
	"\x0fRestoreResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"<\n" +
	"\x17GetRestoreStatusRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"a\n" +
	"\x18GetRestoreStatusResponse\x12E\n" +
	"\bprogress\x18\x01 \x01(\v2).bark.v1alpha1.database.OperationProgressR\bprogress\"[\n" +
	"\x1dListAvailableSnapshotsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x1eListAvailableSnapshotsResponse\x12B\n" +
	"\tsnapshots\x18\x01 \x03(\v2$.bark.v1alpha1.database.SnapshotInfoR\tsnapshots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"K\n" +
	"\x0fTruncateRequest\x128\n" +
	"\x06target\x18\x01 \x01(\v2 .bark.v1alpha1.database.BlockRefR\x06target\"5\n" +
	"\x10TruncateResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"=\n" +
	"\x18GetTruncateStatusRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\x89\x01\n" +
	"\x19GetTruncateStatusResponse\x12E\n" +
	"\bprogress\x18\x01 \x01(\v2).bark.v1alpha1.database.OperationProgressR\bprogress\x12%\n" +
	"\x0eblocks_removed\x18\x02 \x01(\x04R\rblocksRemoved\"C\n" +
	"\x1eStreamOperationProgressRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"h\n" +
	"\x1fStreamOperationProgressResponse\x12E\n" +
	"\bprogress\x18\x01 \x01(\v2).bark.v1alpha1.database.OperationProgressR\bprogress\"\x9a\x02\n" +
	"\x1aGetOperationHistoryRequest\x12K\n" +
	"\vtype_filter\x18\x01 \x01(\x0e2%.bark.v1alpha1.database.OperationTypeH\x00R\n" +
	"typeFilter\x88\x01\x01\x12Q\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2'.bark.v1alpha1.database.OperationStatusH\x01R\fstatusFilter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageTokenB\x0e\n" +
	"\f_type_filterB\x10\n" +
	"\x0e_status_filter\"\x88\x01\n" +
	"\x1bGetOperationHistoryResponse\x12A\n" +
	"\arecords\x18\x01 \x03(\v2'.bark.v1alpha1.database.OperationRecordR\arecords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x18\n" +
	"\x16GetDatabaseInfoRequest\"\xc6\x02\n" +
	"\x17GetDatabaseInfoResponse\x122\n" +
	"\x03tip\x18\x01 \x01(\v2 .bark.v1alpha1.database.BlockRefR\x03tip\x12\x1f\n" +
	"\vblock_count\x18\x02 \x01(\x04R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1f\n" +
	"\voldest_slot\x18\x04 \x01(\x04R\n" +
	"oldestSlot\x122\n" +
	"\x15operation_in_progress\x18\x05 \x01(\bR\x13operationInProgress\x125\n" +
	"\x14current_operation_id\x18\x06 \x01(\tH\x00R\x12currentOperationId\x88\x01\x01\x12\x12\n" +
	"\x04tier\x18\a \x01(\tR\x04tierB\x17\n" +
	"\x15_current_operation_id\";\n" +
	"\x16CancelOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"Z\n" +
	"\x17CancelOperationResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.bark.v1alpha1.database.OperationStatusR\x06status*\xcc\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aOPERATION_STATUS_CANCELLED\x10\x05*\xa0\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_TYPE_SNAPSHOT\x10\x01\x12\x1a\n" +
	"\x16OPERATION_TYPE_RESTORE\x10\x02\x12\x1b\n" +
	"\x17OPERATION_TYPE_TRUNCATE\x10\x03\x12\x19\n" +
	"\x15OPERATION_TYPE_VERIFY\x10\x042\xf9\f\n" +
	"\x0fDatabaseService\x12o\n" +
	"\x0eCreateSnapshot\x12-.bark.v1alpha1.database.CreateSnapshotRequest\x1a..bark.v1alpha1.database.CreateSnapshotResponse\x12x\n" +
	"\x11GetSnapshotStatus\x120.bark.v1alpha1.database.GetSnapshotStatusRequest\x1a1.bark.v1alpha1.database.GetSnapshotStatusResponse\x12l\n" +
	"\rListSnapshots\x12,.bark.v1alpha1.database.ListSnapshotsRequest\x1a-.bark.v1alpha1.database.ListSnapshotsResponse\x12o\n" +
	"\x0eDeleteSnapshot\x12-.bark.v1alpha1.database.DeleteSnapshotRequest\x1a..bark.v1alpha1.database.DeleteSnapshotResponse\x12o\n" +
	"\x0eVerifySnapshot\x12-.bark.v1alpha1.database.VerifySnapshotRequest\x1a..bark.v1alpha1.database.VerifySnapshotResponse\x12Z\n" +
	"\aRestore\x12&.bark.v1alpha1.database.RestoreRequest\x1a'.bark.v1alpha1.database.RestoreResponse\x12u\n" +
	"\x10GetRestoreStatus\x12/.bark.v1alpha1.database.GetRestoreStatusRequest\x1a0.bark.v1alpha1.database.GetRestoreStatusResponse\x12\x87\x01\n" +
	"\x16ListAvailableSnapshots\x125.bark.v1alpha1.database.ListAvailableSnapshotsRequest\x1a6.bark.v1alpha1.database.ListAvailableSnapshotsResponse\x12]\n" +
	"\bTruncate\x12'.bark.v1alpha1.database.TruncateRequest\x1a(.bark.v1alpha1.database.TruncateResponse\x12x\n" +
	"\x11GetTruncateStatus\x120.bark.v1alpha1.database.GetTruncateStatusRequest\x1a1.bark.v1alpha1.database.GetTruncateStatusResponse\x12\x8c\x01\n" +
	"\x17StreamOperationProgress\x126.bark.v1alpha1.database.StreamOperationProgressRequest\x1a7.bark.v1alpha1.database.StreamOperationProgressResponse0\x01\x12~\n" +
	"\x13GetOperationHistory\x122.bark.v1alpha1.database.GetOperationHistoryRequest\x1a3.bark.v1alpha1.database.GetOperationHistoryResponse\x12r\n" +
	"\x0fGetDatabaseInfo\x12..bark.v1alpha1.database.GetDatabaseInfoRequest\x1a/.bark.v1alpha1.database.GetDatabaseInfoResponse\x12r\n" +
	"\x0fCancelOperation\x12..bark.v1alpha1.database.CancelOperationRequest\x1a/.bark.v1alpha1.database.CancelOperationResponseB\xec\x01\n" +
	"\x1acom.bark.v1alpha1.databaseB\rDatabaseProtoP\x01ZEgithub.com/blinklabs-io/bark/proto/v1alpha1/database;databasev1alpha1\xa2\x02\x03BVD\xaa\x02\x16Bark.V1alpha1.Database\xca\x02\x16Bark\\V1alpha1\\Database\xe2\x02\"Bark\\V1alpha1\\Database\\GPBMetadata\xea\x02\x18Bark::V1alpha1::Databaseb\x06proto3"

var (
	file_v1alpha1_database_database_proto_rawDescOnce sync.Once
	file_v1alpha1_database_database_proto_rawDescData []byte
)

func file_v1alpha1_database_database_proto_rawDescGZIP() []byte {
	file_v1alpha1_database_database_proto_rawDescOnce.Do(func() {
		file_v1alpha1_database_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_database_database_proto_rawDesc), len(file_v1alpha1_database_database_proto_rawDesc)))
	})
	return file_v1alpha1_database_database_proto_rawDescData
}

var file_v1alpha1_database_database_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1alpha1_database_database_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_v1alpha1_database_database_proto_goTypes = []any{
	(OperationStatus)(0),                    // 0: bark.v1alpha1.database.OperationStatus
	(OperationType)(0),                      // 1: bark.v1alpha1.database.OperationType
	(*BlockRef)(nil),                        // 2: bark.v1alpha1.database.BlockRef
	(*OperationProgress)(nil),               // 3: bark.v1alpha1.database.OperationProgress
	(*OperationRecord)(nil),                 // 4: bark.v1alpha1.database.OperationRecord
	(*SnapshotInfo)(nil),                    // 5: bark.v1alpha1.database.SnapshotInfo
	(*CreateSnapshotRequest)(nil),           // 6: bark.v1alpha1.database.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),          // 7: bark.v1alpha1.database.CreateSnapshotResponse
	(*GetSnapshotStatusRequest)(nil),        // 8: bark.v1alpha1.database.GetSnapshotStatusRequest
	(*GetSnapshotStatusResponse)(nil),       // 9: bark.v1alpha1.database.GetSnapshotStatusResponse
	(*ListSnapshotsRequest)(nil),            // 10: bark.v1alpha1.database.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),           // 11: bark.v1alpha1.database.ListSnapshotsResponse
	(*DeleteSnapshotRequest)(nil),           // 12: bark.v1alpha1.database.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),          // 13: bark.v1alpha1.database.DeleteSnapshotResponse
	(*VerifySnapshotRequest)(nil),           // 14: bark.v1alpha1.database.VerifySnapshotRequest
	(*VerifySnapshotResponse)(nil),          // 15: bark.v1alpha1.database.VerifySnapshotResponse
	(*RestoreRequest)(nil),                  // 16: bark.v1alpha1.database.RestoreRequest
	(*RestoreResponse)(nil),                 // 17: bark.v1alpha1.database.RestoreResponse
	(*GetRestoreStatusRequest)(nil),         // 18: bark.v1alpha1.database.GetRestoreStatusRequest
	(*GetRestoreStatusResponse)(nil),        // 19: bark.v1alpha1.database.GetRestoreStatusResponse
	(*ListAvailableSnapshotsRequest)(nil),   // 20: bark.v1alpha1.database.ListAvailableSnapshotsRequest
	(*ListAvailableSnapshotsResponse)(nil),  // 21: bark.v1alpha1.database.ListAvailableSnapshotsResponse
	(*TruncateRequest)(nil),                 // 22: bark.v1alpha1.database.TruncateRequest
	(*TruncateResponse)(nil),                // 23: bark.v1alpha1.database.TruncateResponse
	(*GetTruncateStatusRequest)(nil),        // 24: bark.v1alpha1.database.GetTruncateStatusRequest
	(*GetTruncateStatusResponse)(nil),       // 25: bark.v1alpha1.database.GetTruncateStatusResponse
	(*StreamOperationProgressRequest)(nil),  // 26: bark.v1alpha1.database.StreamOperationProgressRequest
	(*StreamOperationProgressResponse)(nil), // 27: bark.v1alpha1.database.StreamOperationProgressResponse
	(*GetOperationHistoryRequest)(nil),      // 28: bark.v1alpha1.database.GetOperationHistoryRequest
	(*GetOperationHistoryResponse)(nil),     // 29: bark.v1alpha1.database.GetOperationHistoryResponse
	(*GetDatabaseInfoRequest)(nil),          // 30: bark.v1alpha1.database.GetDatabaseInfoRequest
	(*GetDatabaseInfoResponse)(nil),         // 31: bark.v1alpha1.database.GetDatabaseInfoResponse
	(*CancelOperationRequest)(nil),          // 32: bark.v1alpha1.database.CancelOperationRequest
	(*CancelOperationResponse)(nil),         // 33: bark.v1alpha1.database.CancelOperationResponse
	(*timestamppb.Timestamp)(nil),           // 34: google.protobuf.Timestamp
}
var file_v1alpha1_database_database_proto_depIdxs = []int32{
	0,  // 0: bark.v1alpha1.database.OperationProgress.status:type_name -> bark.v1alpha1.database.OperationStatus
	34, // 1: bark.v1alpha1.database.OperationProgress.started_at:type_name -> google.protobuf.Timestamp
	34, // 2: bark.v1alpha1.database.OperationProgress.updated_at:type_name -> google.protobuf.Timestamp
	34, // 3: bark.v1alpha1.database.OperationProgress.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 4: bark.v1alpha1.database.OperationRecord.type:type_name -> bark.v1alpha1.database.OperationType
	0,  // 5: bark.v1alpha1.database.OperationRecord.status:type_name -> bark.v1alpha1.database.OperationStatus
	34, // 6: bark.v1alpha1.database.OperationRecord.started_at:type_name -> google.protobuf.Timestamp
	34, // 7: bark.v1alpha1.database.OperationRecord.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 8: bark.v1alpha1.database.SnapshotInfo.tip:type_name -> bark.v1alpha1.database.BlockRef
	34, // 9: bark.v1alpha1.database.SnapshotInfo.created_at:type_name -> google.protobuf.Timestamp
	3,  // 10: bark.v1alpha1.database.GetSnapshotStatusResponse.progress:type_name -> bark.v1alpha1.database.OperationProgress
	5,  // 11: bark.v1alpha1.database.ListSnapshotsResponse.snapshots:type_name -> bark.v1alpha1.database.SnapshotInfo
	34, // 12: bark.v1alpha1.database.DeleteSnapshotResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3,  // 13: bark.v1alpha1.database.GetRestoreStatusResponse.progress:type_name -> bark.v1alpha1.database.OperationProgress
	5,  // 14: bark.v1alpha1.database.ListAvailableSnapshotsResponse.snapshots:type_name -> bark.v1alpha1.database.SnapshotInfo
	2,  // 15: bark.v1alpha1.database.TruncateRequest.target:type_name -> bark.v1alpha1.database.BlockRef
	3,  // 16: bark.v1alpha1.database.GetTruncateStatusResponse.progress:type_name -> bark.v1alpha1.database.OperationProgress
	3,  // 17: bark.v1alpha1.database.StreamOperationProgressResponse.progress:type_name -> bark.v1alpha1.database.OperationProgress
	1,  // 18: bark.v1alpha1.database.GetOperationHistoryRequest.type_filter:type_name -> bark.v1alpha1.database.OperationType
	0,  // 19: bark.v1alpha1.database.GetOperationHistoryRequest.status_filter:type_name -> bark.v1alpha1.database.OperationStatus
	4,  // 20: bark.v1alpha1.database.GetOperationHistoryResponse.records:type_name -> bark.v1alpha1.database.OperationRecord
	2,  // 21: bark.v1alpha1.database.GetDatabaseInfoResponse.tip:type_name -> bark.v1alpha1.database.BlockRef
	0,  // 22: bark.v1alpha1.database.CancelOperationResponse.status:type_name -> bark.v1alpha1.database.OperationStatus
	6,  // 23: bark.v1alpha1.database.DatabaseService.CreateSnapshot:input_type -> bark.v1alpha1.database.CreateSnapshotRequest
	8,  // 24: bark.v1alpha1.database.DatabaseService.GetSnapshotStatus:input_type -> bark.v1alpha1.database.GetSnapshotStatusRequest
	10, // 25: bark.v1alpha1.database.DatabaseService.ListSnapshots:input_type -> bark.v1alpha1.database.ListSnapshotsRequest
	12, // 26: bark.v1alpha1.database.DatabaseService.DeleteSnapshot:input_type -> bark.v1alpha1.database.DeleteSnapshotRequest
	14, // 27: bark.v1alpha1.database.DatabaseService.VerifySnapshot:input_type -> bark.v1alpha1.database.VerifySnapshotRequest
	16, // 28: bark.v1alpha1.database.DatabaseService.Restore:input_type -> bark.v1alpha1.database.RestoreRequest
	18, // 29: bark.v1alpha1.database.DatabaseService.GetRestoreStatus:input_type -> bark.v1alpha1.database.GetRestoreStatusRequest
	20, // 30: bark.v1alpha1.database.DatabaseService.ListAvailableSnapshots:input_type -> bark.v1alpha1.database.ListAvailableSnapshotsRequest
	22, // 31: bark.v1alpha1.database.DatabaseService.Truncate:input_type -> bark.v1alpha1.database.TruncateRequest
	24, // 32: bark.v1alpha1.database.DatabaseService.GetTruncateStatus:input_type -> bark.v1alpha1.database.GetTruncateStatusRequest
	26, // 33: bark.v1alpha1.database.DatabaseService.StreamOperationProgress:input_type -> bark.v1alpha1.database.StreamOperationProgressRequest
	28, // 34: bark.v1alpha1.database.DatabaseService.GetOperationHistory:input_type -> bark.v1alpha1.database.GetOperationHistoryRequest
	30, // 35: bark.v1alpha1.database.DatabaseService.GetDatabaseInfo:input_type -> bark.v1alpha1.database.GetDatabaseInfoRequest
	32, // 36: bark.v1alpha1.database.DatabaseService.CancelOperation:input_type -> bark.v1alpha1.database.CancelOperationRequest
	7,  // 37: bark.v1alpha1.database.DatabaseService.CreateSnapshot:output_type -> bark.v1alpha1.database.CreateSnapshotResponse
	9,  // 38: bark.v1alpha1.database.DatabaseService.GetSnapshotStatus:output_type -> bark.v1alpha1.database.GetSnapshotStatusResponse
	11, // 39: bark.v1alpha1.database.DatabaseService.ListSnapshots:output_type -> bark.v1alpha1.database.ListSnapshotsResponse
	13, // 40: bark.v1alpha1.database.DatabaseService.DeleteSnapshot:output_type -> bark.v1alpha1.database.DeleteSnapshotResponse
	15, // 41: bark.v1alpha1.database.DatabaseService.VerifySnapshot:output_type -> bark.v1alpha1.database.VerifySnapshotResponse
	17, // 42: bark.v1alpha1.database.DatabaseService.Restore:output_type -> bark.v1alpha1.database.RestoreResponse
	19, // 43: bark.v1alpha1.database.DatabaseService.GetRestoreStatus:output_type -> bark.v1alpha1.database.GetRestoreStatusResponse
	21, // 44: bark.v1alpha1.database.DatabaseService.ListAvailableSnapshots:output_type -> bark.v1alpha1.database.ListAvailableSnapshotsResponse
	23, // 45: bark.v1alpha1.database.DatabaseService.Truncate:output_type -> bark.v1alpha1.database.TruncateResponse
	25, // 46: bark.v1alpha1.database.DatabaseService.GetTruncateStatus:output_type -> bark.v1alpha1.database.GetTruncateStatusResponse
	27, // 47: bark.v1alpha1.database.DatabaseService.StreamOperationProgress:output_type -> bark.v1alpha1.database.StreamOperationProgressResponse
	29, // 48: bark.v1alpha1.database.DatabaseService.GetOperationHistory:output_type -> bark.v1alpha1.database.GetOperationHistoryResponse
	31, // 49: bark.v1alpha1.database.DatabaseService.GetDatabaseInfo:output_type -> bark.v1alpha1.database.GetDatabaseInfoResponse
	33, // 50: bark.v1alpha1.database.DatabaseService.CancelOperation:output_type -> bark.v1alpha1.database.CancelOperationResponse
	37, // [37:51] is the sub-list for method output_type
	23, // [23:37] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_v1alpha1_database_database_proto_init() }
func file_v1alpha1_database_database_proto_init() {
	if File_v1alpha1_database_database_proto != nil {
		return
	}
	file_v1alpha1_database_database_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1alpha1_database_database_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1alpha1_database_database_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1alpha1_database_database_proto_msgTypes[26].OneofWrappers = []any{}
	file_v1alpha1_database_database_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_database_database_proto_rawDesc), len(file_v1alpha1_database_database_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_database_database_proto_goTypes,
		DependencyIndexes: file_v1alpha1_database_database_proto_depIdxs,
		EnumInfos:         file_v1alpha1_database_database_proto_enumTypes,
		MessageInfos:      file_v1alpha1_database_database_proto_msgTypes,
	}.Build()
	File_v1alpha1_database_database_proto = out.File
	file_v1alpha1_database_database_proto_goTypes = nil
	file_v1alpha1_database_database_proto_depIdxs = nil
}
